### PR TITLE
DEV-117: Remove code copied from post_zephir_processing

### PR DESCRIPTION
**Pull request by mwarin**
DEV-117 consists of moving some code from the `post_zephir_processing` repo to the `feed_internal` repo.
A PR exists for the additions to `feed_internal`: https://github.com/hathitrust/feed_internal/pull/35
This here is the PR for the corresponding deletions in `post_zephir_processing`. 

## Testing

```
docker compose build
docker compose up -d
docker compose run --rm pz perl t/test_postZephir.t
docker compose run --rm test rspec
docker compose down
```

### CODE REVIEW

**Review by aelkiss — APPROVED** [review]
Looks good but obv. let's not deploy until the feed_internal PR is fixed.

**Review by aelkiss — CHANGES_REQUESTED** [review]
After the discussion today I realized we also need to remove the handling for these files from `monthly_inventory.rb` (e.g. https://github.com/hathitrust/post_zephir_processing/blob/main/lib/monthly_inventory.rb#L31-L32 but there's probably other parts that need to get removed too)

**Comment by mwarin** [comment]
@aelkiss I think that's all of the mentions of `daily_touched` and `groove_incremental` gone from `post_zephir_processing`.

**Review by aelkiss — APPROVED** [review]
Looks good to me. Up to you if you want to try to roll this out while I'm out next week or wait until I'm back the week of the 1st.

**Pull request merged**
